services:
  - type: web
    name: football
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
